### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by CGsama** [LanceLiang2018/Wenku8ToEpub#7]
id1587
```
Traceback (most recent call last):
  File "wenku8toepub.py", line 687, in <module>
  File "wenku8toepub.py", line 523, in get_book
  File "wenku8toepub.py", line 474, in get_book_no_copyright
IndexError: list index out of range
[12884] Failed to execute script 'wenku8toepub' due to unhandled exception!

```

**Comment by chiro2001** [comment]
好像txt解析有点问题…只能暂时忽略错误了

**Comment by webbrain-one** [comment]
Thanks for reporting this! I’ve opened pull request #15 to fix the `IndexError: list index out of range` crash. It adds a guard so the script checks that the list has items before accessing an index in `get_book_no_copyright`, preventing the traceback when the list is empty.

https://github.com/chiro2001/Wenku8ToEpub/pull/15
